import type { ShopifyCustomer } from '@/types/customer'

export const MOCK_CUSTOMER: ShopifyCustomer = {
  id: 'gid://shopify/Customer/dev-test-123',
  email: 'test@example.com',
  firstName: 'Test',
  lastName: 'User',
  phone: '+1234567890',
  acceptsMarketing: true,
  defaultAddress: {
    id: 'gid://shopify/MailingAddress/dev-addr-1',
    firstName: 'Test',
    lastName: 'User',
    company: 'Mizoke',
    address1: '123 Test Street',
    address2: 'Suite 100',
    city: 'Los Angeles',
    province: 'California',
    provinceCode: 'CA',
    country: 'United States',
    countryCodeV2: 'US',
    zip: '90001',
    phone: '+1234567890',
    formatted: ['123 Test Street', 'Suite 100', 'Los Angeles CA 90001', 'United States'],
  },
  addresses: {
    edges: [
      {
        node: {
          id: 'gid://shopify/MailingAddress/dev-addr-1',
          firstName: 'Test',
          lastName: 'User',
          company: 'Mizoke',
          address1: '123 Test Street',
          address2: 'Suite 100',
          city: 'Los Angeles',
          province: 'California',
          provinceCode: 'CA',
          country: 'United States',
          countryCodeV2: 'US',
          zip: '90001',
          phone: '+1234567890',
          formatted: ['123 Test Street', 'Suite 100', 'Los Angeles CA 90001', 'United States'],
        },
      },
      {
        node: {
          id: 'gid://shopify/MailingAddress/dev-addr-2',
          firstName: 'Test',
          lastName: 'User',
          company: null,
          address1: '456 Backup Ave',
          address2: null,
          city: 'San Francisco',
          province: 'California',
          provinceCode: 'CA',
          country: 'United States',
          countryCodeV2: 'US',
          zip: '94102',
          phone: null,
          formatted: ['456 Backup Ave', 'San Francisco CA 94102', 'United States'],
        },
      },
    ],
  },
}
